app/blueprint/main.py
from flask import Blueprint, render_template, current_app, send_from_directory, request, url_for, flash
from flask_login import current_user
from flask_ckeditor import upload_success, upload_fail
from flask_ckeditor.utils import random_filename
from app.models.user import User
from app.models.share import Share
import os
from app.utils import redirect_back
from sqlalchemy.sql.expression import func

main_bp = Blueprint("main", __name__)


@main_bp.route("/")
@main_bp.route("/<int:page>")
def index(page=1):
    # shares = Share.query.order_by(Share.publish_time.desc()).all()
    pagination = Share.query.order_by(Share.publish_time.desc()).paginate(page, 10)
    shares = pagination.items
    return render_template("index.html", shares=shares, pagination=pagination)


@main_bp.route("/avatars/<path:filename>")
def get_avatar(filename):
    return send_from_directory(current_app.config["AVATARS_SAVE_PATH"], filename)


@main_bp.route("/files/<filename>")
def uploaded_files(filename):
    return send_from_directory(current_app.config["UPLOADED_PATH"], filename)


@main_bp.route("/upload", methods=["POST"])
def upload():
    f = request.files.get("upload")
    extension = f.filename.split(".")[-1].lower()
    if extension not in ["jpg", "gif", "png", "jpeg"]:
        return upload_fail(message="Image only!")
    new_filename = random_filename(f.filename)
    f.save(os.path.join(current_app.config["UPLOADED_PATH"], new_filename))
    url = url_for("main.uploaded_files", filename=new_filename)
    return upload_success(url=url)


@main_bp.route("/person/<int:user_id>")
@main_bp.route("/person/<int:user_id>/<int:page>")
def person(user_id, page=1):
    user = User.query.filter_by(id=user_id).first()
    pagination = Share.query.filter_by(author_id=user_id).order_by(Share.publish_time.desc()).paginate(page, 10)
    shares = pagination.items
    return render_template("/person_page.html", shares=shares, pagination=pagination, user=user)


@main_bp.route("/search")
def search():
    q = request.args.get("q")
    if q == "":
        flash("搜索字段不能为空")
        return redirect_back()
    category = request.args.get("category", "user")
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config["SEARCH_RESULT_PER_PAGE"]
    if category == "user":
        pagination = User.query.whooshee_search(q).paginate(page, per_page)
    result = pagination.items

    return render_template("search_result.html", result=result, pagination=pagination, q=q, category=category)


@main_bp.route("/explore")
def explore():
    shares = Share.query.order_by(func.random()).limit(5)
    return render_template("explore.html", shares=shares)


@main_bp.route("/about_site")
def about_site():
    return render_template("about_site.html")

app/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no, maximum-scale=1.0, minimum-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    {% endblock css %}
</head>
<body>
<div>
    {% block head %}
        <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light mb-4">
            <a class="navbar-brand" href="#">
                <img src="{{ url_for('static', filename='web_img/web_icon.svg') }}" width="30" height="30"
                     class="d-inline-block align-top" alt="" loading="lazy"> 遇爱
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.index') }}">最新</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.explore') }}">随缘</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('share.concern_shares') }}">关心</a>
                    </li>
                    {% endif %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.about_site') }}">关于本站</a>
                    </li>
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownQ" role="button"#}
{#                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                            Dropdown#}
{#                        </a>#}
{#                        <div class="dropdown-menu" aria-labelledby="navbarDropdownQ">#}
{#                            <a class="dropdown-item" href="#">Action</a>#}
{#                            <a class="dropdown-item" href="#">Another action</a>#}
{#                            <div class="dropdown-divider"></div>#}
{#                            <a class="dropdown-item" href="#">Something else here</a>#}
{#                        </div>#}
{#                    </li>#}
                </ul>
                {% if current_user.is_authenticated %}
                    <img src="{{ url_for("main.get_avatar", filename=current_user.avatar_s) }}" width="30" height="30"
                         class="d-inline-block align-top" alt="" loading="lazy">
                {% endif %}
                <ul class="navbar-nav mr-left">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ current_user.nick_name }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('share.new_share') }}">新分享</a>
                                <a class="dropdown-item" href="{{ url_for('share.shares', user_id=current_user.id) }}">我的分享</a>
                                <a class="dropdown-item" href="{{ url_for('user.user_following', follow_relation='following', user_id=current_user.id, page=1) }}">
                                    我的关注 <span class="badge badge-primary">{{ current_user.following.count() }}</span>
                                </a>
                                <a class="dropdown-item" href="{{ url_for('user.user_following', follow_relation='followers', user_id=current_user.id, page=1) }}">
                                    我的粉丝 <span class="badge badge-primary">{{ current_user.followers.count() }}</span>
                                </a>
                                <a class="dropdown-item" href="{{ url_for('share.receive_comments', follow_relation='following', user_id=current_user.id, page=1) }}">
                                    评论我的<span class="badge badge-primary">{{ current_user.unread_receive_comments_count() }}</span>
                                </a>
                                <a class="dropdown-item" href="{{ url_for('user.user_info') }}">个人资料</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ url_for('user.logout') }}">退出登录</a>
                            </div>
                        </li>
                    {% else %}
                        <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                        <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
                    {% endif %}
                </ul>

                <form class="form-inline my-2 my-lg-0" action="{{ url_for('main.search') }}">
                    <input class="form-control mr-sm-2" name="q" type="search" placeholder="搜索用户名或昵称" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                </form>
            </div>
        </nav>
    {% endblock head %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
        {% block body %}
        {% endblock body %}

        {% if current_user.is_authenticated %}
            <div id="global-token" token={{ csrf_token() }}></div>
        {% else %}
            <div id="global-token" token=""></div>
        {% endif %}

        {% block script %}
            <script src="{{ url_for('static', filename='js/jquery.3.3.1.min.js') }}"></script>
            <script src="{{ url_for('static', filename='js/bootstrap.bundle.js') }}"></script>
            {{ moment.include_moment(local_js=url_for("static", filename="js/moment-with-locales.js")) }}
            {{ moment.locale(auto_detect=True) }}
            <script src="{{ url_for('static', filename='js/init.js') }}"></script>
        {% endblock script %}
    </div>
    <footer>
        <hr>
        <div class="container">
            {% block foot %}
                <p class="text-center fs-6"><small>遇爱 版权所有</small></p>
                <p class="text-center"><small>用户QQ群 581751428</small> <a target="_blank" href="https://qm.qq.com/cgi-bin/qm/qr?k=3l3Lt6DXvyQAkN60YFQ9q6rkK-cbrFLI&jump_from=webapi"><img border="0" src="//pub.idqqimg.com/wpa/images/group.png" alt="遇爱 年轻人的情感向" title="遇爱 年轻人的情感向"></a> </p>

            {% endblock foot %}
        </div>
    </footer>
</div>
</body>
</html>

app/templates/_macro.html
{# 渲染普通表单字段 #}
{% macro form_field(field, annotation=None) %}
    <div class="form-group">
        {{ field.label(class="control-label") }}
        {% if annotation %}
            {{ annotation | safe }}
        {% endif %}
        {% if field.errors %}
            {% for error in field.errors %}
                <span class='badge badge-danger'>{{ error }}</span>
            {% endfor %}
        {% endif %}
        <div class="">
            {{ field(class="form-control", **kwargs) }}
        </div>
    </div>
{% endmacro %}

{# 渲染check表单字段 #}
{% macro check_field(field) %}
    <div class="form-group">
        <div class="form-check form-check-inline">
          {{ field(class="form-check-input") }}
          {{ field.label(class="form-check-label") }}
        </div>
    </div>
{% endmacro %}


{#渲染分页器 简版#}
{% macro pager(pagination, fragment="") %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-end">
    <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.prev_num, **kwargs) + fragment if pagination.has_prev else '#'}}" tabindex="-1" aria-disabled="true">上一页</a>
    </li>
    <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.next_num, **kwargs) + fragment if pagination.has_next else '#'}}">下一页</a>
    </li>
  </ul>
</nav>
{% endmacro %}


{#渲染分页器 详版#}
{% macro pager_full(pagination, fragment="") %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-end">
    {% for page_num in pagination.iter_pages(left_edge=2, left_current=2, right_current=3, right_edge=2) %}
        {% if page_num %}
        <li class="page-item {% if page_num == pagination.page %}active{% endif %}">
          <a class="page-link" href="{{ url_for(request.endpoint, page=page_num, **kwargs) + fragment}}" tabindex="-1">{{ page_num }}</a>
        </li>
        {% else %}
            <li class="page-item">
              <a class="page-link" href="javascript:void(0)" tabindex="-1" aria-disabled="true">···</a>
            </li>
        {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endmacro %}


{#回复模态框#}
{% macro post_comment(title, id) %}
    <div class="modal fade" id="box_comment" tabindex="-1" aria-labelledby="box_comment" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <p class="modal-title" id="box_commentModalLabel">{{ title }}</p>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary">发布评论</button>
          </div>
        </div>
      </div>
    </div>
{% endmacro %}

app/templates/about_site.html
{% extends "_base.html" %}
{% block body %}

    <div class="jumbotron">
      <h1 class="display-4">遇爱</h1>
      <h1 class="display-6">遇见 X 喜爱</h1>
      <p class="lead">这是一个专注于情感的分享平台</p>

      <hr class="my-4">
      <p class="lead">分享你的情感经历，寻找共鸣和答案</p>
      <p class="lead">交到"心"朋友... ...</p>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="{{ url_for('main.explore') }}" role="button">去探索</a>
      </p>
    </div>

{% endblock body %}

app/templates/concerns.html
{% extends "_base.html" %}
{% from "_macro.html" import pager_full %}
{% block body %}
    <div class="row">
        {% if shares|length == 0 %}
            <div class="col-md-12 mb-3">
                <div class="card">
                    <div class="card-header">
                        小提示
                    </div>
                    <div class="card-body" style="font-size: 16px;">
                        你还没有关注的小宝贝~~<br>
                        这里会列出你所关注的朋友的最新分享。
                    </div>
                </div>
            </div>
        {% endif %}
        {% for share in shares %}
            <div class="col-md-12 mb-3 share-data" data-id={{ share.id }}>
                <div class="card">
                    <div class="card-header" style="background: #e4e6f9">
                        <a href="{{ url_for("main.person", user_id=share.author_id) }}" style="text-decoration: none">
                            <img class="rounded p-1"
                                 src="{{ url_for("main.get_avatar", filename=share.author.avatar_m) }}" width=40 alt="">
                            <span class="align-middle text-dark"
                                  style="font-size:18px; margin-bottom:0">{{ share.author.nick_name }}</span>
                        </a>
                    </div>
                    <div class="card-body">
                        {% if share.img %}
                            <div class="text-left">
                                <img src="{{ url_for("main.uploaded_files", filename=share.img) }}" class="share_img">
                                <span class="align-bottom big_img">[原图]</span>
                            </div>
                            <br>
                        {% endif %}
                        <p class="share">{{ share.content | safe }}</p>
                        <p class="text-right">
                                    <span style="cursor: pointer;" class="like_icon">
                                    {% if current_user.is_authenticated %}
                                        {% if current_user in share.like_users %}
                                            <i class="bi bi-heart-fill praise-del" style="color:red"></i>
                                        {% else %}
                                            <i class="bi bi-heart-fill praise-add"></i>
                                        {% endif %}
                                    {% else %}
                                        <i class="bi bi-heart-fill" data-toggle="modal"
                                           data-target="#loginRequireModal"></i>
                                    {% endif %}

                                        <span class="praise-num">{{ share.like_users_count() }}</span>
                                    </span>

                                    <span style="cursor: pointer;" class="comment_icon ml-2">
                                        <i class="bi bi-chat-right-dots-fill"></i>
                                        <span class="praise-num">{{ share.comments_count() }}</span>
                                    </span>
                        </p>
                        <p class="text-secondary text-right"
                           style="font-size:16px; margin-bottom:0">{{ moment(share.publish_time).format("LLL") }}</p>
                    </div>
                </div>
            </div>


        {% endfor %}

        <!-- 要求登录模态框 -->
        {% include "modal/login_require.html" %}
        <!-- 图片放大模态框 -->
        {% include "modal/share_image.html" %}
    </div>
    {{ pager_full(pagination) }}
{% endblock body %}

app/templates/explore.html
{% extends "_base.html" %}
{% block body %}
<div class="row">
        {% for share in shares %}
            <div class="col-md-12 mb-3 share-data" data-id={{ share.id }} {% if loop.index == 1 %}id="explore"{% endif %}>
                <div class="card">
                    <div class="card-header">
                        <a href="{{ url_for("main.person", user_id=share.author_id) }}" style="text-decoration: none">
                            <img class="rounded p-1" src="{{ url_for("main.get_avatar", filename=share.author.avatar_m) }}" width=40 alt="">
                                <span class="align-middle text-dark" style="font-size:18px; margin-bottom:0">{{ share.author.nick_name }}</span>
                        </a>
                    </div>
                    <div class="card-body">
                        {% if share.img %}
                            <div class="text-left">
                                <img src="{{ url_for("main.uploaded_files", filename=share.img) }}" class="share_img">
                                <span class="align-bottom big_img">[原图]</span>
                            </div>
                            <br>
                        {% endif %}
                        <p class="share">{{ share.content | safe }}</p>
                        <p class="text-right">
                                    <span style="cursor: pointer;" class="like_icon">
                                    {% if current_user.is_authenticated %}
                                        {% if current_user in share.like_users %}
                                            <i class="bi bi-heart-fill praise-del" style="color:red"></i>
                                        {% else %}
                                            <i class="bi bi-heart-fill praise-add"></i>
                                        {% endif %}
                                    {% else %}
                                        <i class="bi bi-heart-fill" data-toggle="modal" data-target="#loginRequireModal"></i>
                                    {% endif %}
                                        <span class="praise-num">{{ share.like_users_count() }}</span>
                                    </span>

                                    <span style="cursor: pointer;" class="comment_icon ml-2">
                                        <i class="bi bi-chat-right-dots-fill"></i>
                                        <span class="praise-num">{{ share.comments_count() }}</span>
                                    </span>

                            </p>
{#                        <p class="text-secondary text-right" style="font-size:16px; margin-bottom:0">{{ moment(share.publish_time).format("LLL") }}</p>#}
                    </div>
                </div>
            </div>


        {% endfor %}

        <a href="{{ url_for('main.explore') }}" class="btn btn-primary fixed-bottom shadow-lg " style="border-radius: 1.5rem; bottom: 84px; right:6%; left: auto;">换一批</a>
        <!-- 要求登录模态框 -->
        {% include "modal/login_require.html" %}
        <!-- 图片放大模态框 -->
        {% include "modal/share_image.html" %}
    </div>

{% endblock body %}

app/templates/index.html
{% extends "_base.html" %}
{% from "_macro.html" import pager %}
{% block body %}
<div class="row">
        {% for share in shares %}
            <div class="col-md-12 mb-3 share-data" data-id={{ share.id }}>
                <div class="card">
                    <div class="card-header">
                        <a href="{{ url_for("main.person", user_id=share.author_id) }}" style="text-decoration: none">
                            <img class="rounded p-1" src="{{ url_for("main.get_avatar", filename=share.author.avatar_m) }}" width=40 alt="">
                                <span class="align-middle text-dark" style="font-size:18px; margin-bottom:0">{{ share.author.nick_name }}</span>
                        </a>
                    </div>
                    <div class="card-body">
                        {% if share.img %}
                            <div class="text-left">
                                <img src="{{ url_for("main.uploaded_files", filename=share.img) }}" class="share_img">
                                <span class="align-bottom big_img">[原图]</span>
                            </div>
                            <br>
                        {% endif %}
                        <p class="share">{{ share.content | safe }}</p>
                        <p class="text-right">
                                    <span style="cursor: pointer;" class="like_icon">
                                    {% if current_user.is_authenticated %}
                                        {% if current_user in share.like_users %}
                                            <i class="bi bi-heart-fill praise-del" style="color:red"></i>
                                        {% else %}
                                            <i class="bi bi-heart-fill praise-add"></i>
                                        {% endif %}
                                    {% else %}
                                        <i class="bi bi-heart-fill" data-toggle="modal" data-target="#loginRequireModal"></i>
                                    {% endif %}
                                        <span class="praise-num">{{ share.like_users_count() }}</span>
                                    </span>

                                    <span style="cursor: pointer;" class="comment_icon ml-2">
                                        <i class="bi bi-chat-right-dots-fill"></i>
                                        <span class="praise-num">{{ share.comments_count() }}</span>
                                    </span>

                            </p>
{#                        <p class="text-secondary text-right" style="font-size:16px; margin-bottom:0">{{ moment(share.publish_time).format("LLL") }}</p>#}
                    </div>
                </div>
            </div>


        {% endfor %}

        <!-- 要求登录模态框 -->
        {% include "modal/login_require.html" %}
        <!-- 图片放大模态框 -->
        {% include "modal/share_image.html" %}

    </div>
    {{ pager(pagination) }}
{% endblock body %}

app/templates/search_result.html
{% extends "_base.html" %}
{% from "_macro.html" import pager_full %}
{% block body %}
<div class="row">
        {% if category=="user" %}
            <div class="col-md-12 mb-3">
                <div class="card">
                    <div class="card-header">
                        搜索 <span class="badge badge-primary" style="font-size: 20px;">{{ q }}</span> 的用户： {{ pagination.total }}
                    </div>
                    <div class="card-body">
                    {% if result|length == 0 %}
                        没有符合的搜索结果~ 不好意思~~
                    {% endif %}
                    {% for r in result %}
                    <div class="col-md-12">
                            <a href="{{ url_for("main.person", user_id=r.id) }}" class="align-bottom text-dark" style="text-decoration: none; text-align: center">
                                <img class="rounded p-1"
                                 src="{{ url_for("main.get_avatar", filename=r.avatar_m) }}" width=40 alt="">
                                <span class="align-middle">{{ r.user_name }}</span>
                                <span class="align-middle">{{ r.nick_name }}</span>
                            </a>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}



        <!-- 要求登录模态框 -->
        {% include "modal/login_require.html" %}

    </div>
    {{ pager_full(pagination, q=q, category=category) }}
{% endblock body %}